//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueueLog
    {
        public int Id { get; set; }
        public string Campaign { get; set; }
        public string Template { get; set; }
        public string CustomerName { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string MailContent { get; set; }
        public string ErrorLog { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    }
}
