//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxEmail
    {
        public long id { get; set; }
        public string CurrentEmail { get; set; }
        public Nullable<System.DateTime> DateEmail { get; set; }
        public string Subject { get; set; }
        public string FromEmailAddress { get; set; }
        public string Body { get; set; }
        public string CurrentUserEmail { get; set; }
        public string OurEmailAddress { get; set; }
        public int Uid { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    }
}
